### ISSUE TITLE
Install Issue - CentOS 7

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#1]
Maybe just me being a n00b, but I figure I might not be the only one to run into the issue.

Clean install of CentOS 7 running in Digital Ocean that was spun up just for this app, went through and installed mariadb, php, apache, all that jazz.

I had an issue getting the `website.com/installwizard.php` bit to start up. I could see website.com, and the CandidATS welcome page, but as soon as I clicked on the install button, I was just getting a blank page

/var/log/httpd/error-log was showing:

```
Class 'PDO' not found in /var/www/html/candidats/lib/ClsNaanalPDO.php on line 8
```

Turns out I just needed to `yum install php-pdo` to get it fixed.

Can mark the issue as closed, just throwing it up here in case anyone else is dumb like me :-)

**Comment by tamilamuthan** [comment]
ss-dsheets,

Thank  you for your effort. This will help others, who face the  same issue.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited
http://auieo.com
