### ISSUE TITLE
Plaintext Password in Sites Listing

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#2]
When navigating to `Settings --> Administration --> Manage Sites --> "Site name"` and viewing the Site Details, you can see the admin login and password details in plaintext.

**Comment by tamilamuthan** [comment]
ss-dsheets,

Super admin only can see  the password. Other admins and  Other site admins cannot see this.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited
http://auieo.com

**Comment by ss-dsheets** [comment]
Solved!
