### ISSUE TITLE
Missing Functionality

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#3]
After install, there are missing tabs and functions that are present in an install of OpenCATS `https://github.com/opencats/OpenCATS.git`

Here is an install of CandidATS, which is missing several features for adding and removing jobs, candidates, etc. Lots of missing tabs up at the top, which are shown in the install of OpenCATS below.
In both cases, the user accessing the page is the core admin user, with full root privileges as determined by `Settings --> Administration --> User Management`

![candidats](https://cloud.githubusercontent.com/assets/10777192/9334726/2b7ebc88-459e-11e5-8d64-2a4f7ecec25e.png)

![opencats2](https://cloud.githubusercontent.com/assets/10777192/9334724/2b55201c-459e-11e5-916b-f63a98433e43.png)
![opencats](https://cloud.githubusercontent.com/assets/10777192/9334725/2b611b42-459e-11e5-834e-c689d1b3d338.png)

**Comment by ss-dsheets** [comment]
Ah, wait a minute, I think I just figured out how Profiles work. Love the implicit deny... any documentation on this that I can read through?

**Comment by tamilamuthan** [comment]
ss-dsheets,

good. you can check http://candidats.auieo.com/forums/topic/candidats-2-0-0-beta for getting started.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited
http://auieo.com

**Comment by ss-dsheets** [comment]
Solved!
