### ISSUE TITLE
PDO Query Execution Error - Viewing Candidate

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#4]
When in the Candidates tab, and clicking on the name of a candidate to view more details, leading to `index.php?m=candidates&a=show&candidateID=1`, an error page pops up displaying the following:

> PDOException Object ( [message:protected] => SQLSTATE[42S22]: Column not found: 1054 Unknown column 'for_id' in 'where clause' [string:Exception:private] => [code:protected] => 42S22 [file:protected] => /var/www/html/candidats/lib/ClsNaanalPDO.php [line:protected] => 124 [trace:Exception:private] => Array ( [0] => Array ( [file] => /var/www/html/candidats/lib/ClsNaanalPDO.php [line] => 124 [function] => execute [class] => PDOStatement [type] => -> [args] => Array ( ) ) [1] => Array ( [file] => /var/www/html/candidats/lib/ClsNaanalPDO.php [line] => 555 [function] => query [class] => ClsNaanalPDO [type] => -> [args] => Array ( [0] => select \* from email_history where for_id=1 and for_module='candidates' ) ) [2] => Array ( [file] => /var/www/html/candidats/lib/DatabaseConnectionPDO.php [line] => 149 [function] => setQuery [class] => ClsNaanalPDO [type] => -> [args] => Array ( [0] => select \* from email_history where for_id=1 and for_module='candidates' ) ) [3] => Array ( [file] => /var/www/html/candidats/lib/DatabaseConnectionPDO.php [line] => 327 [function] => query [class] => DatabaseConnection [type] => -> [args] => Array ( [0] => select \* from email_history where for_id=1 and for_module='candidates' ) ) [4] => Array ( [file] => /var/www/html/candidats/modules/candidates/CandidatesUI.php [line] => 365 [function] => getAllAssoc [class] => DatabaseConnection [type] => -> [args] => Array ( [0] => select \* from email_history where for_id=1 and for_module='candidates' ) ) [5] => Array ( [file] => /var/www/html/candidats/lib/ModuleUtility.php [line] => 170 [function] => show [class] => CandidatesUI [type] => -> [args] => Array ( ) ) [6] => Array ( [file] => /var/www/html/candidats/index.php [line] => 347 [function] => loadModule [class] => ModuleUtility [type] => :: [args] => Array ( [0] => candidates ) ) ) [previous:Exception:private] => [errorInfo] => Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'for_id' in 'where clause' ) ) ; 
> Total Errors:0
> PDO Query execution failed prematurely. Error: 1

Here's a screenshot if that's easier to read:

![screen shot 2015-08-18 at 3 26 08 pm](https://cloud.githubusercontent.com/assets/10777192/9340425/a2e72962-45bd-11e5-9b8f-3baf7685201b.png)

**Comment by tamilamuthan** [comment]
ss-dsheets,

It is known issue.
open the db/upgrade-0.7.0-1.3.2.sql file. And execute all the sql statement in the database. The issue will  be resolved.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited
http://auieo.com

**Comment by ss-dsheets** [comment]
Solved!

**Comment by ajitt210** [comment]
i have same issue.
i also try you suggestion.
but error not resolved.
