### ISSUE TITLE
[Feature Request] HR Data Obfuscation/User-based data viewing privileges

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#5]
Greetings,
   As the sysadmin for this project inside our organization, I may need to perform maintenance or troubleshooting tasks on CandidATS. Our HR team is placing sensitive materials within the app that are on a confiendtial/need-to-know basis that people on my team or in my role shouldn't be able to view or access.

Is there a way to create a privilege group that can basically only be apart of the "Administration" tabs that root/administrator role can see, but not have the access to view any of the employee data or information stored under Dashboard, Activities, Job Orders, Candidates, etc...?

Thanks!

**Comment by tamilamuthan** [comment]
ss-dsheets,

We initially brought the candidates, joborders, company and contact modules under the role and permission. We consider your request and in future release we will extend this to all elements of CandidATS. Feel free to contact at admin@auieo.in for your suggestions.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited
http://auieo.com
