### ISSUE TITLE
[Issue] Editing Job Order Statuses - "Bad Server Information"

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#6]
When attempting to edit any of the fields in a Job Order, such as Owner, Recruiter, Status, Type, Department, etc... it will return a page that states:

```
Bad Server Information
When you perform actions in CATS like editting a candidate or a job order, CATS assigns numbers to each record that uniquely identifies it. For example, a candidate "Steve Smith" may be identified by the number 101. 

The action you're attempting to perform has a unique number like this attached to it. CATS cannot find a record with the number you provided. The record may have been deleted, you may have inadvertently logged off or an incorrect number may have been provided to you.

It's ok! CATS can't complete whatever action you requested; but chances are, if you click the back button and refresh the page and try again it will work just fine.
```

![candidats](https://cloud.githubusercontent.com/assets/10777192/10529218/ef2e0186-7369-11e5-9889-5fb616f590a3.png)

Changing from privilege level or role doesn't affect the issue, it's consistent across all users.

**Comment by tamilamuthan** [comment]
Hi,

Try updating the latest stable version https://sourceforge.net/projects/candidats/files/latest/download?source=files.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited

**Comment by ss-dsheets** [comment]
Looks like you linked me to v2.0.0 Alpha. My instance is on 2.0.0 Beta, and it looks like the latest release here is "2.0.0 RC1" Is that the current version?

Thanks!

==EDIT== Wait, hang on, I might be dumb... the README.md from the version you linked says Alpha on it, but all of the versions say that. I'm on v2.0.0 Beta, which one should I grab?==

**Comment by tamilamuthan** [comment]
Hi,

The latest release is 2.0.0 Stable. It is in 
https://sourceforge.net/projects/candidats

with regard,
R. Tamil Amuthan
Auieo Software Private Limited

**Comment by tamilamuthan** [comment]
Hi,

Now the latest stable version released. Please update this. Many bugs 
cleared. It is released at https://sourceforge.net/projects/candidats

with regards,
R. Tamil Amuthan
Auieo Software Private Limited

**Comment by ss-dsheets** [comment]
Updating to `Stable` resolved the issue.
