### ISSUE TITLE
[ISSUE] Install stops at "Loading Extras" 

### ISSUE THREAD

**Issue by ss-dsheets** [tamilamuthan/candidats#7]
Hello again!

![screen shot 2015-10-19 at 9 44 51 am](https://cloud.githubusercontent.com/assets/10777192/10579507/788fecb2-7646-11e5-8d2e-f013683dafa4.png)

So I'm attempting to update from `RC1` to `Stable`, and for that process I've moved my main install directory and replaced it with all the new files from the `Stable` release. Nothing from the previous install is present except for the database, (mariadb on CentOS 7)

When moving through the install, I have all green `Success` markers, yet when I arrive to Step 6, `Loading Extras` it will display a loading wheel, then the display will become blank on the page as shown above.

Permissions and ownership of `../candidats/` have been given to apache, and set to 0755

There's no output in either httpd or php-fpm's error logs. 

Thanks for your help!

**Comment by tamilamuthan** [comment]
Hi,

Can you give me access to your server? I will resolve the issue. Since 
we are giving 1 month free high priority support, you can use this for a 
month. We will resolve all the issues for you.

with regards,
R. Tamil Amuthan
Auieo Software Private Limited

**Comment by ss-dsheets** [comment]
There's enough private company data in the database that I can't give external access to the server, development or production environments.

Would you be able to detail what is causing this to happen?

**Comment by tamilamuthan** [comment]
I don't find the issue here. Can you create a development server with 
empty data and give me the access? I will clear the issue.

**Comment by ss-dsheets** [comment]
By moving the `INSTALL_BLOCK` file from the previous installation into the new directory, I was able to bypass the installer and log back into my instance.
